### ISSUE TITLE
'Property RotVelocity must be defined in Bin: \Workspace\*!'

### ISSUE THREAD

**Issue by trussive** [CloneTrooper1019/Roblox-File-Format#5]
I'm getting this only if I put a Part in Workspace and saving.

I've tried setting it before, however I still got the error.

**Comment by CloneTrooper1019** [comment]
Let me know if this is still happening with the latest version.
It might be related to that error that was happening 2 weeks ago.

**Comment by CloneTrooper1019** [comment]
Will be closing this in a few days if I don't hear back.
