### ISSUE TITLE
I don't know how to add this to my project.

### ISSUE THREAD

**Issue by Sccepter** [CloneTrooper1019/Roblox-File-Format#6]
Hello! I am trying to add this into a C# Console App .NET Framework. I am used to adding class libraries, but this has many files. I also can't run the Roblox file format solution. Thanks!

**Comment by CloneTrooper1019** [comment]
You can add a reference to the built DLL file from the reference manager.
![image](https://user-images.githubusercontent.com/3926900/117086920-9a524980-ad13-11eb-9f09-face5706bd72.png)
